environment: pet-environment-homolog
### Project Settings
componentId: teste-14
cluster_name: teste-14
owner: group:default/admin
instance_type: t3.medium
volume_size: 30
keypair_name: platform_kp
### Network Settings
vpc_id: vpc-051721395ecf1f7aa
domain: pet.platform.vee.codes
hostedZoneId: Z0420419WKDTM5OR7WI9
subnet_id: subnet-04dda6147dd9410f1
### Ingress Settings
ingress_window: true
basic_auth: true
issuer_type: staging
email: platformss@vee.codes
### Terraform Backend Settings
terraformStateBucketName: veecode-homolog-terraform-state
terraformStateBucketRegion: us-east-1
infracost: false
### Publish Settings
host: github.com
destination: veecode-homolog/teste-14
specPublish: ${{ parameters.specPublish | parseRepoUrl | pick('owner') }}/${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
specPublishRepo: ${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
specPublishBranch: 
### Observability Settings
observability_window: true
## Cluster configuration 
cluster_obs_name: obs-central-apr
cluster_obs_domain: platform.vee.codes
cluster_obs_public_ip: 54.92.227.240